#Parameter yang digunakan untuk setup Database (MySQL)
version: '3.8' #Versi Docker yang digunakan
services:
    #Setup environment apache
    php-apache-environment:
        container_name: php-apache
        build:
            context: ./php
            dockerfile: Dockerfile
        depends_on:
            - db
        volumes:
            - ./php/src:/var/www/html/
        ports:
            - 7077:80 #Port 80 yang di forward ke 7077
    #Setup untuk database
    db:
        container_name: db #Container akan dinamakan dengan "db"
        image: mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: MYSQL_ROOT_PASSWORD
            MYSQL_DATABASE: Redlock #Nama database yang akan digunakan adalah "Redlock"
            MYSQL_USER: MYSQL_USER
            MYSQL_PASSWORD: MYSQL_PASSWORD
        ports:
            - "9906:3306"
    #Setup untuk menampilkan phpmyadmin.
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        ports:
            - '8080:80'
        restart: always
        environment:
            PMA_HOST: db
        depends_on:
            - db
    #Setup Untuk jenkins.
    jenkins:
      build:
         context: ./Jenkins
         dockerfile: Dockerfile
      ports:
         - 8001:8080